apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: health-records
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: fast-ssd
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: health-records
type: Opaque
data:
  mysql-root-password: cGFzc3dvcmQ= # password
  mysql-user-password: dXNlcnBhc3N3b3Jk # userpassword
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: health-records
data:
  my.cnf: |
    [mysqld]
    default-storage-engine=INNODB
    character-set-server=utf8mb4
    collation-server=utf8mb4_unicode_ci
    max_connections=200
    innodb_buffer_pool_size=1G
    innodb_log_file_size=256M
    innodb_flush_log_at_trx_commit=2
    innodb_flush_method=O_DIRECT
    query_cache_size=0
    query_cache_type=0
    slow_query_log=1
    slow_query_log_file=/var/log/mysql/slow-query.log
    long_query_time=2
    log_error=/var/log/mysql/error.log
    general_log=0
    
    # Binary logging
    log-bin=mysql-bin
    binlog_format=ROW
    expire_logs_days=7
    max_binlog_size=100M
    
    # InnoDB settings
    innodb_file_per_table=1
    innodb_open_files=400
    innodb_io_capacity=400
    innodb_read_io_threads=4
    innodb_write_io_threads=4
    
    # Connection settings
    wait_timeout=600
    interactive_timeout=600
    max_allowed_packet=64M
    
    # Security
    skip-name-resolve
    bind-address=0.0.0.0
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: health-records
  labels:
    app: mysql
spec:
  serviceName: mysql-service
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
          name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-password
        - name: MYSQL_DATABASE
          value: "healthrecords"
        - name: MYSQL_USER
          value: "healthuser"
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-user-password
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
        - name: mysql-config-volume
          mountPath: /etc/mysql/conf.d
        - name: mysql-logs
          mountPath: /var/log/mysql
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - mysql
            - -h
            - localhost
            - -u
            - root
            - -p${MYSQL_ROOT_PASSWORD}
            - -e
            - "SELECT 1"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        securityContext:
          runAsUser: 999
          runAsGroup: 999
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
            add:
            - CHOWN
            - DAC_OVERRIDE
            - FOWNER
            - SETGID
            - SETUID
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
      - name: mysql-config-volume
        configMap:
          name: mysql-config
      - name: mysql-logs
        emptyDir: {}
      securityContext:
        fsGroup: 999
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: health-records
  labels:
    app: mysql
spec:
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
    name: mysql
  selector:
    app: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  namespace: health-records
  labels:
    app: mysql
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
    name: mysql
  selector:
    app: mysql